### ISSUE TITLE
Error no file named config.json found in directory PowerPaint_v2/PowerPaint_Brushnet

### ISSUE THREAD

**Issue by lucDoom** [zhuang2002/PowerPaint#76]
Thanks for giving training code!
In train_ppt2_bn.py line 590 : pipe.brushnet = BrushNetModel.from_pretrained(args.powerpaint_model_name_or_path)
I give args.powerpaint_model_name_or_path as https://huggingface.co/JunhaoZhuang/PowerPaint-v2-1/tree/main/PowerPaint_Brushnet, and got error: Error no file named config.json found in directory PowerPaint_v2/PowerPaint_Brushnet
Can I replace this function with: load_model(pipe.brushnet,'/ProjectRoot/image_outpainting/PowerPaint-main/official_pretrained/PowerPaint_v2/PowerPaint_Brushnet/diffusion_pytorch_model.safetensors')
or training must rely on config. json. 
If config. json is needed, where can I get it？

**Comment by zengyh1900** [comment]
Hi @lucDoom,

Thank you for your interest.

1. Since I have refactored the code in the `dev` branch, the original released weights cannot be loaded directly.
2. Yes, you can use `load_model` instead to load the previously released weights. But I DO NOT recommend you using in this way, because the logic of adding learnable tokens can be slightly different from the previous version (e.g., the order of added tokens)
3. In fact, to train your own PowerPaint, you don't need to start from the previous PowerPaint-v2 weights. The only thing you need to do is to prepare the dataset and run the following command:

   ```
   accelerate launch --config_file configs/acc.yaml train_ppt2_bn.py --config configs/ppt2_bn.yaml
   ```

   You can refer to `configs/ppt2_bn.yaml` for more details. You only need to specify `pretrained_model_path` as `sd15` according to the configuration file.

**Comment by lucDoom** [comment]
thx for ur help @zengyh1900
I have another question: I write my own inference code from app.py for image outpaiting locally from main brach.
if the code had been refactored, does  the inference code need to be changed?
I found that in dev brach there are some changes, eg. there is no more powerpaint.utils.utils.TokenizerWrapper
So can you share new inference code for the dev branch? thanks a lot!
